# Generated by Django 4.0.6 on 2022-07-08 20:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('role', models.CharField(choices=[('REGULAR', "Regular - Can't delete members"), ('ADMIN', 'Admin - Can delete members')], default='REGULAR', max_length=7)),
            ],
            options={
                'permissions': (('Regular', "Can't delete members"), ('Admin', 'Can delete members')),
            },
        ),
    ]
